public class try_catch {
    public static void main(String[] args) {
        try {
            HomeWork25_11.calculate();
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
    }
}
